import type React from "react";
import { useState } from "react";
import { ArrowDownRight, ArrowUpRight, Award, BadgeCheck, BookOpen, CheckCircle2, ChevronRight, CircleDot, Download, ExternalLink, Github, Globe2, KeyRound, Linkedin, Mail, Menu, Network, Phone, Radar, Server, Shield, ShieldAlert, Terminal, X } from "lucide-react";
import { useTheme } from "@/contexts/ThemeContext";

const resumeUrl = "https://drive.google.com/file/d/1MVfEGlpA9LqgKTXk0QCK9LoTbnvfRIl0/view?usp=sharing";
const projects = [
  { number: "01", title: "Metasploitable 2 Penetration Test", type: "Offensive Security Lab", description: "End-to-end assessment covering reconnaissance, vulnerability scanning, exploitation, post-exploitation, and privilege escalation through vsftpd, Samba, and system misconfigurations.", tags: ["Nmap", "Metasploit", "Linux", "CVSS"], icon: ShieldAlert },
  { number: "02", title: "Healthcare Web/API Security Assessment", type: "Authorized Security Research", description: "Manual assessment of a healthcare information system and REST API using controlled role-based accounts, with findings mapped to OWASP and actionable remediation guidance.", tags: ["Burp Suite", "OWASP", "REST API", "Authorization"], icon: Globe2, link: "https://github.com/Mohamed-Ashmawyy/evolex-his-security-assessment" },
  { number: "03", title: "Huawei Firewall Hardening Lab", type: "Network Security", description: "Configured a Huawei USG6000V firewall with 15+ ACLs, DMZ/LAN/WAN segmentation, stateful traffic filtering, and encrypted IPsec VPN access for an enterprise simulation.", tags: ["Huawei eNSP", "ACLs", "IPsec", "Network Security"], icon: Network },
  { number: "04", title: "Security Automation Toolkit", type: "Python & Bash Development", description: "Built BigRecon for automated subdomain enumeration and directory brute-forcing, alongside a Python packet sniffer for raw TCP/IP traffic analysis and security experiments.", tags: ["Python", "Bash", "BigRecon", "TCP/IP"], icon: Terminal, link: "https://github.com/Mohamed-Ashmawyy/" },
];
const certifications = [
  ["RHCSA", "Red Hat Certified System Administrator", "ITI · May 2025"], ["HCIA", "HCIA Security", "Huawei / NTI · Mar 2025"], ["CCNA", "Cisco Certified Network Associate", "Cisco NetAcad · Jan 2025"], ["Sprints", "Microsoft Cybersecurity Camp", "Sprints x Microsoft · Jul 2025"], ["NTI", "Penetration Testing & Network Security", "Cybersecurity Training · Oct 2025"], ["eJPT", "Junior Penetration Tester Preparation", "Udemy · Aug 2026"],
];
const skillGroups = [
  { title: "Offensive Security", icon: Radar, items: ["Reconnaissance", "Vulnerability Assessment", "Exploitation", "Privilege Escalation", "Web & Network Pentesting"] },
  { title: "Security Tooling", icon: Terminal, items: ["Nmap", "Metasploit", "Burp Suite", "ffuf / BigRecon", "SQLmap · Nikto · Wireshark"] },
  { title: "Systems & Networks", icon: Server, items: ["Kali Linux", "Red Hat", "Windows", "Active Directory Security", "Network Enumeration"] },
  { title: "Frameworks & Reporting", icon: BookOpen, items: ["OWASP Top 10", "MITRE ATT&CK", "CVE / CVSS", "Digital Forensics", "Actionable Security Reports"] },
];
function Heading({ eyebrow, title, body }: { eyebrow: string; title: string; body: string }) { return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{body}</p></div>; }
function ExtLink({ href, children, className = "" }: { href: string; children: React.ReactNode; className?: string }) { return <a className={className} href={href} target="_blank" rel="noreferrer">{children}</a>; }

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false); const [sent, setSent] = useState(false); const { theme, toggleTheme } = useTheme();
  const jump = (id: string) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  const submitForm = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const subject = encodeURIComponent(String(data.get("subject") || "Cybersecurity collaboration")); const body = encodeURIComponent(`Name: ${data.get("name")}\nEmail: ${data.get("email")}\n\n${data.get("message")}`); window.location.href = `mailto:mohamedd.ashmawyy@gmail.com?subject=${subject}&body=${body}`; setSent(true); };
  const nav = [["about", "About"], ["skills", "Skills"], ["projects", "Projects"], ["experience", "Experience"], ["contact", "Contact"]];
  return <main>
    <nav className="site-nav container"><button className="brand" onClick={() => jump("home")} aria-label="Go home"><span className="brand-mark"><Shield size={18} /></span><span><strong>MAA</strong><small>SECURITY PORTFOLIO</small></span></button><div className={`nav-links ${menuOpen ? "is-open" : ""}`}>{nav.map(([id, label]) => <button key={id} onClick={() => jump(id)}>{label}</button>)}</div><div className="nav-actions"><button className="theme-toggle" onClick={toggleTheme} aria-label="Toggle theme"><span className={theme === "dark" ? "active" : ""}>D</span><span className={theme === "light" ? "active" : ""}>L</span></button><ExtLink className="nav-cta" href={resumeUrl}>Resume <Download size={15} /></ExtLink><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X /> : <Menu />}</button></div></nav>
    <section className="hero" id="home"><div className="hero-grid" /><div className="container hero-inner"><div className="hero-copy"><div className="status-pill"><span className="status-dot" /> Available for cybersecurity opportunities</div><p className="hero-kicker">CYBERSECURITY ANALYST <span>/</span> PENETRATION TESTER</p><h1>Breaking systems<br /><em>to secure them.</em></h1><p className="hero-lead">I investigate how systems fail, turn vulnerabilities into clear risk, and help teams build more resilient digital environments.</p><div className="hero-actions"><button className="button button-primary" onClick={() => jump("projects")}>Explore my work <ArrowUpRight size={17} /></button><button className="button button-ghost" onClick={() => jump("contact")}>Let&apos;s connect <ArrowDownRight size={17} /></button></div><div className="hero-meta"><span><CircleDot size={14} /> Cairo, Egypt</span><span><CheckCircle2 size={14} /> Open to opportunities</span></div></div><div className="hero-visual"><div className="visual-orbit orbit-one" /><div className="visual-orbit orbit-two" /><div className="shield-core"><Shield size={86} strokeWidth={1.1} /><span>SECURE<br />THE<br />SURFACE</span></div><div className="terminal-card terminal-top"><span className="terminal-dot green" /> assessment_status<strong>ACTIVE</strong></div><div className="terminal-card terminal-bottom"><span className="terminal-dot amber" /> CVSS SCORE<strong>9.1 CRITICAL</strong></div><span className="visual-code code-one">0x4F2A</span><span className="visual-code code-two">OWASP_10</span><span className="visual-code code-three">/root/analyst</span></div></div><div className="hero-footer container"><span>Scroll to investigate</span><div className="hero-line" /><span>01 — 06</span></div></section>
    <section className="about-section section-pad" id="about"><div className="container about-grid"><div><Heading eyebrow="01 · Profile" title="Curious by nature. Precise by practice." body="I’m Mohamed Abdelmonem Ashmawy, a junior cybersecurity analyst and penetration tester focused on practical offensive security, network defense, and security automation." /><a className="text-link" href="mailto:mohamedd.ashmawyy@gmail.com">Start a conversation <ArrowUpRight size={16} /></a></div><div className="profile-panel"><div className="panel-header"><span>ANALYST PROFILE</span><span className="panel-live"><span className="status-dot" /> ONLINE</span></div><div className="profile-row"><span>Focus</span><strong>Offensive Security</strong></div><div className="profile-row"><span>Experience</span><strong>Practical labs & internship</strong></div><div className="profile-row"><span>Education</span><strong>B.Sc. Computer Science</strong></div><div className="profile-row"><span>Graduation</span><strong>Jul 2026 · Excellent project</strong></div><div className="profile-note"><KeyRound size={18} /><span>My goal is simple: make technical risk understandable, actionable, and harder to exploit.</span></div></div></div></section>
    <section className="skills-section section-pad" id="skills"><div className="container"><Heading eyebrow="02 · Capabilities" title="A practical security toolkit." body="From the first packet to the final report, I work across the assessment lifecycle with a focus on evidence, repeatability, and responsible disclosure." /><div className="skills-grid">{skillGroups.map(({ title, icon: Icon, items }, index) => <article className="skill-card" key={title}><div className="skill-top"><span>0{index + 1}</span><Icon size={22} /></div><h3>{title}</h3><ul>{items.map(item => <li key={item}><ChevronRight size={14} />{item}</li>)}</ul></article>)}</div></div></section>
    <section className="projects-section section-pad" id="projects"><div className="container"><div className="section-heading project-heading"><div><span className="eyebrow">03 · Selected work</span><h2>Proof lives in the details.</h2></div><p>Hands-on projects that combine offensive security, network engineering, automation, and professional reporting.</p></div><div className="projects-grid">{projects.map(({ number, title, type, description, tags, icon: Icon, link }) => <article className="project-card" key={title}><div className="project-card-top"><span>{number}</span><Icon size={24} /></div><p className="project-type">{type}</p><h3>{title}</h3><p className="project-description">{description}</p><div className="tag-list">{tags.map(tag => <span key={tag}>{tag}</span>)}</div>{link ? <ExtLink className="project-link" href={link}>View on GitHub <ExternalLink size={15} /></ExtLink> : <span className="project-link muted-link">Documented assessment <BadgeCheck size={15} /></span>}</article>)}</div></div></section>
    <section className="experience-section section-pad" id="experience"><div className="container experience-grid"><Heading eyebrow="04 · Experience" title="Learning through real constraints." body="My experience combines structured cybersecurity training, independent labs, and an internship where technical findings had to become clear, defensible reports." /><div className="timeline"><div className="timeline-item"><span className="timeline-marker" /><div className="timeline-date">MAY 2025 — JUN 2025</div><h3>Cybersecurity Intern <span>@ Prodigy InfoTech</span></h3><p>Completed practical ethical-hacking, scripting, and vulnerability-assessment tasks covering OWASP Top 10, privilege escalation, and network enumeration. Produced structured reports with evidence, impact, and remediation recommendations.</p></div><div className="timeline-item"><span className="timeline-marker" /><div className="timeline-date">SEP 2022 — JUL 2026</div><h3>Bachelor&apos;s in Computer Science <span>@ Obour Higher Institute</span></h3><p>Graduated with a Good overall grade and an Excellent graduation project focused on enterprise network simulation, routing, switching, network services, and hands-on implementation.</p></div></div></div></section>
    <section className="certs-section section-pad"><div className="container"><div className="section-heading project-heading"><div><span className="eyebrow">05 · Credentials</span><h2>Built on disciplined learning.</h2></div><p>Certifications and training that support my practical approach to systems, networks, and offensive security.</p></div><div className="certs-grid">{certifications.map(([short, title, issuer]) => <article className="cert-card" key={title}><Award size={20} /><div><span>{short}</span><h3>{title}</h3><p>{issuer}</p></div></article>)}</div></div></section>
    <section className="contact-section section-pad" id="contact"><div className="container contact-grid"><div><Heading eyebrow="06 · Contact" title="Have a surface worth testing?" body="Whether you are building a security program, validating an application, or looking for a curious analyst to join your team, I would like to hear from you." /><div className="contact-links"><a href="mailto:mohamedd.ashmawyy@gmail.com"><Mail size={18} /> mohamedd.ashmawyy@gmail.com</a><a href="tel:+201061906438"><Phone size={18} /> +20 106 190 6438</a><ExtLink href="https://www.linkedin.com/in/mohamedashmawyy"><Linkedin size={18} /> LinkedIn <ExternalLink size={14} /></ExtLink><ExtLink href="https://github.com/Mohamed-Ashmawyy/"><Github size={18} /> GitHub <ExternalLink size={14} /></ExtLink></div></div><form className="contact-form" onSubmit={submitForm}><div className="form-row"><label>Name<input required name="name" placeholder="Your name" /></label><label>Email<input required name="email" type="email" placeholder="you@example.com" /></label></div><label>Subject<input required name="subject" placeholder="Security assessment / opportunity" /></label><label>Message<textarea required name="message" rows={5} placeholder="Tell me what you are working on..." /></label><button className="button button-primary" type="submit">{sent ? "Opening your email client" : "Send message"} <ArrowUpRight size={16} /></button><small>This form opens a pre-filled email. No data is stored on this site.</small></form></div></section>
    <footer className="site-footer"><div className="container footer-inner"><div className="footer-brand"><span className="brand-mark"><Shield size={16} /></span><div><strong>Mohamed Ashmawy</strong><small>Cybersecurity Analyst · Penetration Tester</small></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Mohamed Abdelmonem Ashmawy</span><button onClick={() => jump("home")} aria-label="Back to top">Back to top <ArrowUpRight size={14} /></button></div></div></footer>
  </main>;
}
